.PHONY: help build start stop test test-env

# Shell that make should use
SHELL:=bash

setup:
	./setup.sh

help: ## http://marmelab.com/blog/2016/02/29/auto-documented-makefile.html
	@grep -E '^[a-zA-Z0-9_%/-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

test: ## Make a test run against the latest image
	pytest tests

repo-structure: ## Create public/private repository pair 
	git remote add private-repo https://github.com/{{ github_private_repo }}
	git remote add public-repo https://github.com/{{ github_public_repo }}
	git remote rm origin
	git fetch private-repo
	git branch -u private-repo/private
	git checkout --orphan public
	git fetch public-repo
	git checkout Private

GH_VERSION=2.30.0
GH_URL=https://github.com/cli/cli/releases/download/v${GH_VERSION}/gh_${GH_VERSION}_linux_amd64.tar.gz
GH_DIR=/opt/conda/bin
install-gh: ## place 
	wget "${GH_URL}" -O - | tar xvzf - -C ${GH_DIR} gh_${GH_VERSION}_linux_amd64/bin/gh --strip-components=2
